LittlerootTown_OldGym_MapScripts::
	.byte 0


LittlerootTown_OldGym_EventScript_GymStatue::
# 4 "data/maps/LittlerootTown_OldGym/scripts.pory"
	lockall
# 5 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_0
# 6 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_1
# 7 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_2
# 8 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_3
# 9 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_4
# 10 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_5
# 11 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_6
# 12 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_7
# 13 "data/maps/LittlerootTown_OldGym/scripts.pory"
	msgbox LittlerootTown_OldGym_EventScript_GymStatue_Text_8
# 14 "data/maps/LittlerootTown_OldGym/scripts.pory"
	releaseall
	return


LittlerootTown_OldGym_EventScript_GymStatue_Text_0:
# 5 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "LITTLEROOT POKéMON GYM\p$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_1:
# 6 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "BIRCH'S CERTIFIED TRAINERS:\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_2:
# 7 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "STEVEN\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_3:
# 8 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "WALLACE\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_4:
# 9 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "PHOEBE\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_5:
# 10 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "WINONA\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_6:
# 11 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "FLANNERY\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_7:
# 12 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "BRAWLY\n$"

LittlerootTown_OldGym_EventScript_GymStatue_Text_8:
# 13 "data/maps/LittlerootTown_OldGym/scripts.pory"
	.string "ROXANNE\n$"
