LittlerootTown_BirchsWarehouse_MapScripts::
	.byte 0


LittlerootTown_BirchsWarehouse_EventScript_PaperStack::
# 4 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	lockall
# 5 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	msgbox LittlerootTown_BirchsWarehouse_EventScript_PaperStack_Text_0
# 6 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	releaseall
	return


LittlerootTown_BirchsWarehouse_EventScript_Naughty::
# 10 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	lockall
# 11 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	msgbox LittlerootTown_BirchsWarehouse_EventScript_Naughty_Text_0
# 12 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	releaseall
	return


LittlerootTown_BirchsWarehouse_EventScript_Computer::
# 16 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	lockall
# 17 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	msgbox LittlerootTown_BirchsWarehouse_EventScript_Computer_Text_0
# 18 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	releaseall
	return


LittlerootTown_BirchsWarehouse_EventScript_Bookshelf::
# 22 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	lockall
# 23 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	msgbox LittlerootTown_BirchsWarehouse_EventScript_Bookshelf_Text_0
# 24 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	releaseall
	return


LittlerootTown_BirchsWarehouse_EventScript_PaperStack_Text_0:
# 5 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	.string "It's a random stack of papers.$"

LittlerootTown_BirchsWarehouse_EventScript_Naughty_Text_0:
# 11 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	.string "Eh? There's an adult comic here!$"

LittlerootTown_BirchsWarehouse_EventScript_Computer_Text_0:
# 17 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	.string "It has a spreadsheet of the items stored\nin the warehouse.$"

LittlerootTown_BirchsWarehouse_EventScript_Bookshelf_Text_0:
# 23 "data/maps/LittlerootTown_BirchsWarehouse/scripts.pory"
	.string "It's different books and journals that\nare archived here.$"
